FROM ocaml/opam@sha256:3392c09686e089098aec8ec48243271758738c768dd0faadef30caaf1d238071

LABEL maintainer="Reto Buerki <reet@codelabs.ch>"
LABEL description="Build environment for Muen-enabled MirageOS/Solo5 Unipi website unikernel"

USER root
RUN mv /usr/bin/opam-2.5 /usr/bin/opam
USER opam

RUN cd /home/opam/opam-repository \
	&& git fetch origin master \
	&& git reset --hard 493123878a032e3f829b102f34e8690b3b2a4fd4 \
	&& opam pin add solo5 https://github.com/codelabs-ch/solo5.git#1443b0608061 \
	&& opam update \
	&& opam install -y solo5 mirage.4.11.0 ocaml-solo5

# clone mirage-skeleton and prepare dependencies.
RUN git clone -b codelabs https://github.com/codelabs-ch/mirage-skeleton \
	&& cd mirage-skeleton/applications/static_website_tls \
	&& git reset --hard 6dbd88712b0f81ebef9bfdcec9e1ace48284bd19 \
	&& eval $(opam env) \
	&& mirage configure -t muen \
	&& make \
	&& mv dist/https.muen $HOME/

# clone unipi and prepare dependencies.
RUN git clone -b with-kv-mirage411 https://github.com/roburio/unipi.git \
	&& cd unipi \
	&& git reset --hard 3b019c413be79c5acde6628ad5e0f85022eec6c9 \
	&& eval $(opam env) \
	&& mirage configure -t muen \
	&& make

CMD [ "bash" ]
